#include "Buzzer.hpp"

Buzzer::Buzzer(PinBuzzer pinBuzzer, uint8_t pinGND, uint16_t frequence500k_7){
    if (frequence500k_7 == 0){
        tempsActive_ = 0;
    }
    else {
        tempsActive_ = static_cast<uint16_t>(500000/frequence500k_7);
    }
    pin_ = pinBuzzer;
    switch(pin_) {
        case PinBuzzer::B04:
        TCNT0 = 0;
        OCR0A = tempsActive_/periodeCLKTimer02;
        TCCR0A |= (1 << COM0A0) | (1 << WGM01);
        TCCR0B |= (1 << CS02);
        DDRB |= (1 << PB3) | (1 << (pinGND - 1));
        break;
    case PinBuzzer::B05:
        TCNT0 = 0;
        OCR0A = tempsActive_/periodeCLKTimer02;
        TCCR0A |= (1 << COM0B0) | (1 << WGM01);
        TCCR0B |= (1 << CS02);
        DDRB |= (1 << PB4) | (1 << (pinGND - 1));
        break;
    case PinBuzzer::D15:
        TCNT1 = 0;
        OCR1A = tempsActive_;
        TCCR1A |= (1 << COM1B0);
        TCCR1B |= (1 << CS11) | (1 << WGM12);
        DDRD |= (1 << PD4) | (1 << (pinGND - 1));
        break;
    case PinBuzzer::D16:
        TCNT1 = 0;
        OCR1A = tempsActive_;
        TCCR1A |= (1 << COM1A0);
        TCCR1B |= (1 << CS11) | (1 << WGM12);
        DDRD |= (1 << PD5) | (1 << (pinGND - 1));
        break;
    case PinBuzzer::D27:
        TCNT2 = 0;
        OCR2A = tempsActive_/periodeCLKTimer02;
        TCCR2A |= (1 << COM2B0) | (1 << WGM21);
        TCCR2B |= (1 << CS22) | (1 << CS21);
        DDRD |= (1 << PD6) | ((1 << (pinGND - 1)));
        break;
    case PinBuzzer::D28:
        TCNT2 = 0;
        OCR2A = tempsActive_/periodeCLKTimer02;
        TCCR2A |= (1 << COM2A0) | (1 << WGM21);
        TCCR2B |= (1 << CS22) | (1 << CS21);
        DDRD |= (1 << PD7) | ((1 << (pinGND - 1)));
        break;
    default:
        break;
    }
};
void Buzzer::setFrequence(uint16_t frequence500k_7){
    if (frequence500k_7 == 0){
        tempsActive_ = 0;
    }
    else {
        tempsActive_ = static_cast<uint16_t>(500000/frequence500k_7);
    }
    switch(pin_) {
        case PinBuzzer::B04:
            OCR0A = tempsActive_/periodeCLKTimer02;
            break;
        case PinBuzzer::B05:
            OCR0A = tempsActive_/periodeCLKTimer02;
            break;
        case PinBuzzer::D15:
            OCR1A = tempsActive_;
            break;
        case PinBuzzer::D16:
            OCR1A = tempsActive_;
            break;
        case PinBuzzer::D27:
            OCR2A = tempsActive_/periodeCLKTimer02;
            break;
        case PinBuzzer::D28:
            OCR2A = tempsActive_/periodeCLKTimer02;
            break;
        default:
            break;
    }
};
// void Buzzer::jouerPirateDesCaraibes(){
//     Buzzer::setFrequence(330);
//     _delay_ms(125);
//     Buzzer::setFrequence(392);
//     _delay_ms(125);
//     Buzzer::setFrequence(440);
//     _delay_ms(250);
//     Buzzer::setFrequence(440);
//     _delay_ms(125);
//     Buzzer::setFrequence(0);
//     _delay_ms(125);
//     Buzzer::setFrequence(440);
//     _delay_ms(125);
//     Buzzer::setFrequence(494);
//     _delay_ms(125);
//     Buzzer::setFrequence(523);
//     _delay_ms(250);
//     Buzzer::setFrequence(523);
//     _delay_ms(125);
//     Buzzer::setFrequence(0);
//     _delay_ms(125);
//     Buzzer::setFrequence(523);
//     _delay_ms(125);
//     Buzzer::setFrequence(587);
//     _delay_ms(125);
//     Buzzer::setFrequence(494);
//     _delay_ms(250);
//     Buzzer::setFrequence(494);
//     _delay_ms(125);
//     Buzzer::setFrequence(0);
//     _delay_ms(125);
//     Buzzer::setFrequence(440);
//     _delay_ms(125);
//     Buzzer::setFrequence(392);
//     _delay_ms(125);
//     Buzzer::setFrequence(440);
//     _delay_ms(375);
//     Buzzer::setFrequence(0);
//     _delay_ms(125);
//     Buzzer::setFrequence(330);
//     _delay_ms(125);
//     Buzzer::setFrequence(392);
//     _delay_ms(125);
//     Buzzer::setFrequence(440);
//     _delay_ms(250);
//     Buzzer::setFrequence(440);
//     _delay_ms(125);
//     Buzzer::setFrequence(0);
//     _delay_ms(125);
//     Buzzer::setFrequence(440);
//     _delay_ms(125);
//     Buzzer::setFrequence(494);
//     _delay_ms(125);
//     Buzzer::setFrequence(523);
//     _delay_ms(250);
//     Buzzer::setFrequence(523);
//     _delay_ms(125);
//     Buzzer::setFrequence(0);
//     _delay_ms(125);
//     Buzzer::setFrequence(523);
//     _delay_ms(125);
//     Buzzer::setFrequence(587);
//     _delay_ms(125);
//     Buzzer::setFrequence(494);
//     _delay_ms(250);
//     Buzzer::setFrequence(494);
//     _delay_ms(125);
//     Buzzer::setFrequence(0);
//     _delay_ms(125);
//     Buzzer::setFrequence(440);
//     _delay_ms(125);
//     Buzzer::setFrequence(392);
//     _delay_ms(125);
//     Buzzer::setFrequence(440);
//     _delay_ms(375);
//     Buzzer::setFrequence(0);
//     _delay_ms(125);
//     Buzzer::setFrequence(330);
//     _delay_ms(125);
//     Buzzer::setFrequence(392);
//     _delay_ms(125);
//     Buzzer::setFrequence(440);
//     _delay_ms(250);
//     Buzzer::setFrequence(440);
//     _delay_ms(125);
//     Buzzer::setFrequence(0);
//     _delay_ms(125);
//     Buzzer::setFrequence(440);
//     _delay_ms(125);
//     Buzzer::setFrequence(494);
//     _delay_ms(125);
//     Buzzer::setFrequence(523);
//     _delay_ms(250);
//     Buzzer::setFrequence(523);
//     _delay_ms(125);
//     Buzzer::setFrequence(0);
//     _delay_ms(125);
//     Buzzer::setFrequence(523);
//     _delay_ms(125);
//     Buzzer::setFrequence(587);
//     _delay_ms(125);
//     Buzzer::setFrequence(494);
//     _delay_ms(250);
//     Buzzer::setFrequence(494);
//     _delay_ms(125);
//     Buzzer::setFrequence(0);
//     _delay_ms(125);
//     Buzzer::setFrequence(440);
//     _delay_ms(125);
//     Buzzer::setFrequence(392);
//     _delay_ms(125);
//     Buzzer::setFrequence(440);
//     _delay_ms(375);
//     Buzzer::setFrequence(0);
//     _delay_ms(125);
//     Buzzer::setFrequence(330);
//     _delay_ms(125);
//     Buzzer::setFrequence(392);
//     _delay_ms(125);
//     Buzzer::setFrequence(440);
//     _delay_ms(250);
//     Buzzer::setFrequence(440);
//     _delay_ms(125);
//     Buzzer::setFrequence(0);
//     _delay_ms(125);
//     Buzzer::setFrequence(440);
//     _delay_ms(125);
//     Buzzer::setFrequence(494);
//     _delay_ms(125);
//     Buzzer::setFrequence(523);
//     _delay_ms(250);
//     Buzzer::setFrequence(523);
//     _delay_ms(125);
//     Buzzer::setFrequence(0);
//     _delay_ms(125);
//     Buzzer::setFrequence(523);
//     _delay_ms(125);
//     Buzzer::setFrequence(587);
//     _delay_ms(125);
//     Buzzer::setFrequence(494);
//     _delay_ms(250);
//     Buzzer::setFrequence(0);
//     _delay_ms(125);
//     Buzzer::setFrequence(0);
//     _delay_ms(375);
//     Buzzer::setFrequence(587);
//     _delay_ms(250);
//     Buzzer::setFrequence(0);
//     _delay_ms(125);
//     Buzzer::setFrequence(0);
//     _delay_ms(375);
//     Buzzer::setFrequence(659);
//     _delay_ms(250);
//     Buzzer::setFrequence(0);
//     _delay_ms(125);
//     Buzzer::setFrequence(0);
//     _delay_ms(375);
//     Buzzer::setFrequence(587);
//     _delay_ms(125);
//     Buzzer::setFrequence(587);
//     _delay_ms(125);
//     Buzzer::setFrequence(0);
//     _delay_ms(125);
//     Buzzer::setFrequence(784);
//     _delay_ms(125);
//     Buzzer::setFrequence(0);
//     _delay_ms(125);
//     Buzzer::setFrequence(659);
//     _delay_ms(125);
//     Buzzer::setFrequence(587);
//     _delay_ms(125);
//     Buzzer::setFrequence(0);
//     _delay_ms(125);
//     Buzzer::setFrequence(0);
//     _delay_ms(375);
//     Buzzer::setFrequence(587);
//     _delay_ms(250);
//     Buzzer::setFrequence(0);
//     _delay_ms(125);
//     Buzzer::setFrequence(0);
//     _delay_ms(375);
//     Buzzer::setFrequence(523);
//     _delay_ms(250);
//     Buzzer::setFrequence(0);
//     _delay_ms(125);
//     Buzzer::setFrequence(0);
//     _delay_ms(375);
//     Buzzer::setFrequence(494);
//     _delay_ms(125);
//     Buzzer::setFrequence(523);
//     _delay_ms(125);
//     Buzzer::setFrequence(0);
//     _delay_ms(125);
//     Buzzer::setFrequence(494);
//     _delay_ms(125);
//     Buzzer::setFrequence(0);
//     _delay_ms(125);
//     Buzzer::setFrequence(440);
//     _delay_ms(500);
//     Buzzer::setFrequence(659);
//     _delay_ms(250);
//     Buzzer::setFrequence(0);
//     _delay_ms(125);
//     Buzzer::setFrequence(0);
//     _delay_ms(375);
//     Buzzer::setFrequence(698);
//     _delay_ms(250);
//     Buzzer::setFrequence(0);
//     _delay_ms(125);
//     Buzzer::setFrequence(0);
//     _delay_ms(375);
//     Buzzer::setFrequence(659);
//     _delay_ms(125);
//     Buzzer::setFrequence(659);
//     _delay_ms(125);
//     Buzzer::setFrequence(0);
//     _delay_ms(125);
//     Buzzer::setFrequence(784);
//     _delay_ms(125);
//     Buzzer::setFrequence(0);
//     _delay_ms(125);
//     Buzzer::setFrequence(659);
//     _delay_ms(125);
//     Buzzer::setFrequence(587);
//     _delay_ms(125);
//     Buzzer::setFrequence(0);
//     _delay_ms(125);
//     Buzzer::setFrequence(0);
//     _delay_ms(375);
//     Buzzer::setFrequence(587);
//     _delay_ms(250);
//     Buzzer::setFrequence(0);
//     _delay_ms(125);
//     Buzzer::setFrequence(0);
//     _delay_ms(375);
//     Buzzer::setFrequence(523);
//     _delay_ms(250);
//     Buzzer::setFrequence(0);
//     _delay_ms(125);
//     Buzzer::setFrequence(0);
//     _delay_ms(375);
//     Buzzer::setFrequence(494);
//     _delay_ms(125);
//     Buzzer::setFrequence(523);
//     _delay_ms(125);
//     Buzzer::setFrequence(0);
//     _delay_ms(125);
//     Buzzer::setFrequence(494);
//     _delay_ms(125);
//     Buzzer::setFrequence(0);
//     _delay_ms(125);
//     Buzzer::setFrequence(440);
//     _delay_ms(500);
// };

// void Buzzer::jouerMarioBros(){
//     Buzzer::setFrequence(659);
// _delay_ms(125);
// Buzzer::setFrequence(659);
// _delay_ms(125);
// Buzzer::setFrequence(0);
// _delay_ms(125);
// Buzzer::setFrequence(659);
// _delay_ms(125);
// Buzzer::setFrequence(0);
// _delay_ms(125);
// Buzzer::setFrequence(523);
// _delay_ms(125);
// Buzzer::setFrequence(659);
// _delay_ms(125);
// Buzzer::setFrequence(0);
// _delay_ms(125);
// Buzzer::setFrequence(784);
// _delay_ms(125);
// Buzzer::setFrequence(0);
// _delay_ms(125);
// Buzzer::setFrequence(0);
// _delay_ms(125);
// Buzzer::setFrequence(0);
// _delay_ms(125);
// Buzzer::setFrequence(392);
// _delay_ms(125);
// Buzzer::setFrequence(0);
// _delay_ms(125);
// Buzzer::setFrequence(0);
// _delay_ms(125);
// Buzzer::setFrequence(0);
// _delay_ms(125);
// Buzzer::setFrequence(523);
// _delay_ms(125);
// Buzzer::setFrequence(0);
// _delay_ms(125);
// Buzzer::setFrequence(0);
// _delay_ms(125);
// Buzzer::setFrequence(392);
// _delay_ms(125);
// Buzzer::setFrequence(0);
// _delay_ms(125);
// Buzzer::setFrequence(0);
// _delay_ms(125);
// Buzzer::setFrequence(330);
// _delay_ms(125);
// Buzzer::setFrequence(0);
// _delay_ms(125);
// Buzzer::setFrequence(0);
// _delay_ms(125);
// Buzzer::setFrequence(440);
// _delay_ms(125);
// Buzzer::setFrequence(0);
// _delay_ms(125);
// Buzzer::setFrequence(494);
// _delay_ms(125);
// Buzzer::setFrequence(0);
// _delay_ms(125);
// Buzzer::setFrequence(466);
// _delay_ms(125);
// Buzzer::setFrequence(440);
// _delay_ms(125);
// Buzzer::setFrequence(0);
// _delay_ms(125);
// Buzzer::setFrequence(392);
// _delay_ms(125);
// Buzzer::setFrequence(659);
// _delay_ms(125);
// Buzzer::setFrequence(784);
// _delay_ms(125);
// Buzzer::setFrequence(880);
// _delay_ms(125);
// Buzzer::setFrequence(0);
// _delay_ms(125);
// Buzzer::setFrequence(698);
// _delay_ms(125);
// Buzzer::setFrequence(784);
// _delay_ms(125);
// Buzzer::setFrequence(0);
// _delay_ms(125);
// Buzzer::setFrequence(659);
// _delay_ms(125);
// Buzzer::setFrequence(0);
// _delay_ms(125);
// Buzzer::setFrequence(523);
// _delay_ms(125);
// Buzzer::setFrequence(587);
// _delay_ms(125);
// Buzzer::setFrequence(494);
// _delay_ms(125);
// Buzzer::setFrequence(0);
// _delay_ms(125);
// Buzzer::setFrequence(0);
// _delay_ms(125);
// Buzzer::setFrequence(523);
// _delay_ms(125);
// Buzzer::setFrequence(0);
// _delay_ms(125);
// Buzzer::setFrequence(392);
// _delay_ms(125);
// Buzzer::setFrequence(0);
// _delay_ms(125);
// Buzzer::setFrequence(0);
// _delay_ms(125);
// Buzzer::setFrequence(330);
// _delay_ms(125);
// Buzzer::setFrequence(0);
// _delay_ms(125);
// Buzzer::setFrequence(0);
// _delay_ms(125);
// Buzzer::setFrequence(440);
// _delay_ms(125);
// Buzzer::setFrequence(0);
// _delay_ms(125);
// Buzzer::setFrequence(494);
// _delay_ms(125);
// Buzzer::setFrequence(0);
// _delay_ms(125);
// Buzzer::setFrequence(466);
// _delay_ms(125);
// Buzzer::setFrequence(440);
// _delay_ms(125);
// Buzzer::setFrequence(0);
// _delay_ms(125);
// Buzzer::setFrequence(392);
// _delay_ms(125);
// Buzzer::setFrequence(659);
// _delay_ms(125);
// Buzzer::setFrequence(784);
// _delay_ms(125);
// Buzzer::setFrequence(880);
// _delay_ms(125);
// Buzzer::setFrequence(0);
// _delay_ms(125);
// Buzzer::setFrequence(698);
// _delay_ms(125);
// Buzzer::setFrequence(784);
// _delay_ms(125);
// Buzzer::setFrequence(0);
// _delay_ms(125);
// Buzzer::setFrequence(659);
// _delay_ms(125);
// Buzzer::setFrequence(0);
// _delay_ms(125);
// Buzzer::setFrequence(523);
// _delay_ms(125);
// Buzzer::setFrequence(587);
// _delay_ms(125);
// Buzzer::setFrequence(494);
// _delay_ms(125);
// Buzzer::setFrequence(0);
// _delay_ms(125);
// };
